### PR TITLE
[WIP] Generated by Swagger Codegen

### PR DESCRIPTION
**Pull request by karser**
The api client is generated by the [Swagger Codegen](https://github.com/swagger-api/swagger-codegen) project:

- API version: 0.20.10
- Build package: io.swagger.codegen.v3.generators.php.PhpClientCodegen

### How to generate:

Download [swagger-codegen](https://github.com/swagger-api/swagger-codegen):
```
wget http://central.maven.org/maven2/io/swagger/codegen/v3/swagger-codegen-cli/3.0.7/swagger-codegen-cli-3.0.7.jar -O swagger-codegen-cli.jar
``` 
 
and run the following:
```
java -jar swagger-codegen-cli.jar generate \
   -i http://127.0.0.1:8980/swagger.json \
   -l php \
   -c .swagger-config.json \
   -o .
```

where `-c .swagger-config.json` is config with php options. See all options:
```
java -jar swagger-codegen-cli.jar config-help -l php
```

### CODE REVIEW

**Comment by karser** [comment]
Hi @pierre,

The quality of the generated code isn't excellent but It is viable. As long as we don't need to maintain it's okay I guess.

While fixing tests I encountered an issue: `$tenantApi->createTenant($tenant, ....); ` returns null, although the response status is 201 but payload is zero.
I noticed in the log the Location header:
image
So I need to write a guzzle middleware which will be following this kind of redirect, makes sense?

Also, what does this message mean `INFO: 138 * Server out-bound response` ? Is this an error? Why is the status 201 then?

**Comment by karser** [comment]
Done. Now `createTenant` and `createAccount` work as expected. Here how the entire setup looks like:
image

Yeah, a lot of yak shaving. I think we need to move all this boilerplate to a client wrapper, so it will look like:
```
        $client = new KillbillClient();
        $client->getTenantApi()->createTenant($tenant, ...);
        $client->getAccountApi()->createAccount($account, ...);
```

**Comment by karser** [comment]
Much easier now
image

**Comment by karser** [comment]
Hi @pierre,

I'm fixing ServerInvoiceTest and I'm stuck on this isssue: the second invoice isn't created after 31 days, although the default payment method is set and the subscription is created. Please advise.

image

After 31 days it fetches only 1 invoice
image

Although it creates an entitlement:
image

**Comment by karser** [comment]
There are only 2 tests fail. Both of them are related to the previous message.
image

**Comment by pierre** [comment]
Hey @karser,

> The quality of the generated code isn't excellent but It is viable. As long as we don't need to maintain it's okay I guess.

Indeed, we had the same conclusion for the Java, Go and Python versions. That being said, as long as it works, it's probably good enough (and we can always have a wrapper, as you mentioned).

> There are only 2 tests fail. Both of them are related to the previous message.

👍 I'm going to setup CircleCI and look at it.

I've also switched the base branch to `work-for-release-0.20.x`. The PR is already too large for Github to handle. As soon as we have a stable CI build, I'll merge it, so that subsequent PRs are easier to review.

**Comment by karser** [comment]
Do you ideas why invoice is not created? There is something wrong in setup I guess but I don't have enough experience with killbill.

>I'm going to setup CircleCI and look at it.

I was thinking of implementing record requests and then mock them for Travis.
Do you want to launch live killbill instance on CircleCI?

What do you think of swagger-gen vs openapi-generator?

I found some issues in swagger-gen.
1. Wrong BigDecimal type. I reported this issue https://github.com/swagger-api/swagger-codegen/issues/9353 
2.  Minor issues although affecting DX. They all are marked as TODO in the tests. For example:
```
      //TODO: must be createAccountTags([$tag1, $tag2], ...)
        $accountTags = $this->client->getAccountApi()->createAccountTags(
            json_encode([$tag1->getId(), $tag2->getId()]),
            self::USER,
            $account->getAccountId(),
            self::REASON,
            self::COMMENT
        );
```
or
```
        //TODO: must be createAccountCustomFields([$cf1, $cf2], ...)
        $customFieldsJson = '['.implode(',', [$cf1, $cf2]).']';
        $this->client->getAccountApi()->createAccountCustomFields($customFieldsJson, self::USER, $account->getAccountId(), self::REASON, self::COMMENT);
```

I tried switching to openapi-generator version 3 and 4. It fixed issues 1 and 2, although introduced other ones:
1. The order of function arguments were totally different (and not convenient). For example `method($enity, createdBy, reason, and lot of optional boolean arguments)` became
`method($enity, lot of optional boolean arguments, createdBy, reason)`
2. The generated codebases got increased by ~10%

**Comment by pierre** [comment]
> Do you ideas why invoice is not created? There is something wrong in setup I guess but I don't have enough experience with killbill.

Impossible to tell until I set it up and go through the logs :-)

> I was thinking of implementing record requests and then mock them for Travis.
> Do you want to launch live killbill instance on CircleCI?

Yes: there is certainly value in having pre-recoded requests/responses, but having a couple of real integration tests against a real Kill Bill server is best.

> What do you think of swagger-gen vs openapi-generator?

Never used `openapi-generator` but I'd rather stick to https://github.com/swagger-api/swagger-codegen since we already use it everywhere else.

> 1. Wrong BigDecimal type. I reported this issue [swagger-api/swagger-codegen#9353](https://github.com/swagger-api/swagger-codegen/issues/9353)

👍 

> 2. Minor issues although affecting DX. They all are marked as TODO in the tests. For example:
> 
> ```
>       //TODO: must be createAccountTags([$tag1, $tag2], ...)
>         $accountTags = $this->client->getAccountApi()->createAccountTags(

What is the issue exactly?

Note that the pattern of having several APIs (e.g. `accountApi`), one per Swagger resource, is very much driven by the Swagger schema itself. Take a look at the Java for instance:

```
Tags result = accountApi.createAccountTags(accountId, 
                                           ImmutableList.<UUID>of(autoPayOffId), 
                                           requestOptions);
```

See https://killbill.github.io/slate/?java#account-add-tags-to-account.

**Comment by karser** [comment]
openapi is an interface and swagger is an implementation.
openapi-generator is a fork of swagger-gen driven by the community. I don't have a preference here because I discovered those generator tools last Friday :)

>What is the issue exactly?

It throws an error if you pass an array of IDs. 
`createAccountTags([$tag1->getId(), $tag2->getId()], ...),`

I'm passing json as a workaround.
`createAccountTags(json_encode([$tag1->getId(), $tag2->getId()]), ...),`

Since this is fixed in openapi, we might backport this fix to swagger-gen templates.

**Comment by karser** [comment]
>Note that the pattern of having several APIs (e.g. accountApi), one per Swagger resource

Misunderstanding is here :)
I didn't mean they should be plain functions. I meant it should accept an array of IDs instead of JSON.

**Comment by pierre** [comment]
> It throws an error if you pass an array of IDs.
> `createAccountTags([$tag1->getId(), $tag2->getId()], ...),`

Oh, I see.

> > Note that the pattern of having several APIs (e.g. accountApi), one per Swagger resource
> 
> Misunderstanding is here :)
> I didn't mean they should be plain functions. I meant it should accept an array of IDs instead of JSON.

Got it 👍 

CircleCI has been enabled on `master`: if you merge `master` back into your branch, we should get a CI build triggered. I'll then take a look at the logs.

**Comment by karser** [comment]
Pipelines, awesome! 2 tests failed, exactly as if they run on my local.

**Comment by karser** [comment]
@pierre All tests pass on my local! 
Did you enable test mode on CircleCI?
Clock mock doesn't work there: `Killbill\Client\Swagger\ApiException: Unable to mock the server date. Status: 404, Message: ` 

I have another question: what is the more correct approach when creating subscription? Both options work.
- option 1. specify planName
- option 2. specify productName, category, perdiod and priceList
image

**Comment by karser** [comment]
I unified user-agent. It is set in `.swagger-config.json`. Don't forget to run swagger-gen (described in readme).
image

Tests pass. I guess now it can be merged, right?

**Comment by pierre** [comment]
> I have another question: what is the more correct approach when creating subscription? Both options work.
>
> option 1. specify planName
> option 2. specify productName, category, perdiod and priceList

option 1 is recommended. option 2 is the legacy API, but still supported for backward compatibility.

> Tests pass. I guess now it can be merged, right?

Yup, thanks for your work! 🎉

**Comment by karser** [comment]
Argh, forgot to include in readme how to use the api client wrapper that I added.

**Pull request merged**
