### PR TITLE
Fixes parsing issues with complex/deep types, errors

### PR DESCRIPTION
**Pull request by GregOriol**
This PR mostly fixes various parsing issues:
- fixed response parsing in case of error (ex: http 400, 404, ...)
- fixed some parsing issues on complex types like arrays (java List), regenerated types

Also, some more cleanup of code style
And adds some implementations: CustomField, InvoiceDryRun, RolledUpUsage, SubscriptionUsageRecord

### CODE REVIEW

**Comment by MaxGfeller** [comment]
It's really hard to review this PR because there are so many changes. I'd prefer it if you could make separate PRs for these changes (logger, server independence etc.).

But generally looks good to me, so it's up to you @pierre

**Comment by pierre** [comment]
@MaxGfeller Thanks. FWIW, I also took a look at individual commits.

@GregOriol I'll merge this one as-is, but moving forward, could you make separate PRs so it's easier to review (although hopefully, we won't have much style churn anymore)? Also, for new endpoints, let's make sure to add new tests.

**Comment by GregOriol** [comment]
Sorry, a lot of ideas, things are moving fast, should be more structured from now on :-)

**Pull request merged**
