### PR TITLE
Generated fields against killbill-0.20.10

### PR DESCRIPTION
**Pull request by karser**
This PR fixes https://github.com/killbill/killbill-client-php/issues/34 and makes more tests passing (against killbill v0.20.10 instance).

Before:
```
PHPUnit 4.8.36 by Sebastian Bergmann and contributors.

.EEEE.F.EEEEE.EEEEEEEEEEEEEE

Tests: 28, Assertions: 5, Errors: 23, Failures: 1.
```

After:
```
PHPUnit 4.8.36 by Sebastian Bergmann and contributors.

.E.EF.F.EEE...E.E.EF.EEEEEE.

Tests: 28, Assertions: 196, Errors: 14, Failures: 3.
```

### CODE REVIEW

**Comment by pierre** [comment]
Hi @karser, thank you for this.

Starting with 0.20.x, our client libraries can now be generated from Swagger directly via `swagger-codegen` (the Swagger file can be downloaded at http://127.0.0.1:8080/swagger.json): https://github.com/swagger-api/swagger-codegen/blob/master/README.md

It would probably make sense now to switch over to this, instead of tweaking the files manually. We never had a chance to do it unfortunately and update this repo, which is why master is still compatible only with 0.18.x.

**Comment by karser** [comment]
Hi @pierre . Thanks for the response. 

I'm trying to integrate killbill into my project and likely I'll continue working on this PR and try to make the tests pass.

>can now be generated from Swagger directly ... instead of tweaking the files manually

What do you mean by manually? I didn't tweak the files but generated models using `killbill-java-parser`
Does the result that swagger produces differ from the one produced by java-parser? Does generate CRUD methods too?

>master is still compatible only with 0.18.x.

Yeah, I realized it later how tests pass in travis - there are mocked responses that are used when `ENV=local` is specified.

**Comment by pierre** [comment]
> What do you mean by manually? I didn't tweak the files but generated models using `killbill-java-parser`

`killbill-java-parser` was a project we wrote pre-Swagger days and it only takes care of generating the models (JSON objects). You would still need to fix the actual API implementations (e.g. `src/Account.php`) to make the library work on 0.20.x. To do so, you will have to read the source code and/or follow the doc from https://killbill.github.io/slate/.

`swagger-codegen` would take care of this automatically.

> Does the result that swagger produces differ from the one produced by java-parser?

Yes, the function names would be quite different (match the Swagger `operationId`).

> Does generate CRUD methods too?

It generates methods as defined by the API (`swagger.yml`).

> I'm trying to integrate killbill into my project and likely I'll continue working on this PR and try to make the tests pass.

You're more than welcome to continue down that road but it's a larger effort than switching to `swagger-codegen`. Also, it's not necessarily a direction we'd like to go long term.

**Comment by karser** [comment]
I see, I just generated php client using the swagger generator, it seems very promising. It generated not only models but API CRUDs and tests with empty methods. So we can switch to this new structure and adopt the old tests. wdyt?

I'll create another PR with new structure and let's continue the discussion there then.

**Comment by karser** [comment]
I see, the old client takes care of it. First, it calls `$this->createRequest` and then `$this->getFromResponse` which attempts to get `$responseHeaders['Location']`

**Comment by pierre** [comment]
Closing in favor of https://github.com/killbill/killbill-client-php/pull/36.

**Pull request closed without merging**
